#!/usr/bin/env python3
"""Dependency-free static build. Run from any directory; see README for publishing."""
from pathlib import Path
from html import escape
import json, os, re, argparse
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
C = json.loads((ROOT / 'site.config.json').read_text())
IMAGES = json.loads((ROOT / 'assets/image-dimensions.json').read_text())
SITE = os.environ.get('SITE_URL', C['site_url']).rstrip('/')
INDEX = os.environ.get('INDEXABLE', str(C['indexable'])).lower() == 'true'
if not SITE.startswith('https://') or urlparse(SITE).query or urlparse(SITE).fragment:
    raise ValueError('SITE_URL must be an HTTPS URL without query or fragment')
CURRENT = ''
OUTPUT = {}
PAGES = []
PHONE = C['phone_display']

def e(value): return escape(str(value), quote=True)
def link(path=''):
    if path.startswith(('https:', 'mailto:', 'tel:', '#')): return path
    return ('../' * len(CURRENT.strip('/').split('/')) if CURRENT else './') + path.lstrip('/')
def absolute(path=''): return SITE + '/' + path.lstrip('/')
def icon(name='arrow'):
    paths = {
        'arrow': '<path d="M5 12h14M13 6l6 6-6 6"/>',
        'up': '<path d="M6 18 18 6M6 6h12v12"/>',
        'phone': '<path d="m7 3 3 5-3 3c2 3 3 4 6 6l3-3 5 3c0 3-2 5-5 4C8 19 5 16 3 8 2 5 4 3 7 3Z"/>',
        'pin': '<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
        'check': '<path d="m5 12 4 4L19 6"/>',
        'shield': '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
        'bike': '<circle cx="5" cy="16" r="4"/><circle cx="19" cy="16" r="4"/><path d="m5 16 5-8 4 8H5m14 0L15 4h-3M8 8h4"/>',
        'truck': '<path d="M2 7h12v11H2zM14 11h4l4 4v3h-8M5 7l4-4h6"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',
        'car': '<path d="m4 10 3-5h10l3 5 2 2v6H2v-6l2-2Zm0 0h16M6 14h2m8 0h2M5 18v2m14-2v2"/>',
        'clock': '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
        'chat': '<path d="M21 11a9 9 0 0 1-9 9c-2 0-3 0-5-1l-5 2 2-5a9 9 0 1 1 17-5Z"/><path d="M8 10h8M8 14h5"/>',
        'menu': '<path d="M4 7h16M4 12h16M4 17h16"/>',
        'close': '<path d="m6 6 12 12M6 18 18 6"/>',
        'sun': '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',
        'route': '<circle cx="6" cy="6" r="3"/><circle cx="18" cy="18" r="3"/><path d="M9 6h6a4 4 0 0 1 0 8H9a4 4 0 0 0 0 8"/>',
    }
    return f'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{paths.get(name,paths["arrow"])}</svg>'

def img(name, alt, priority=False, cls=''):
    dims=IMAGES[name]
    large=link('assets/images/'+name+'.webp')
    small=link('assets/images/'+name+'-640.webp')
    sources=f'{small} {dims["smallWidth"]}w, {large} {dims["width"]}w' if dims['smallWidth']!=dims['width'] else f'{large} {dims["width"]}w'
    return f'<img src="{large}" srcset="{sources}" sizes="(max-width: 650px) calc(100vw - 36px), (max-width: 900px) 50vw, 640px" alt="{e(alt)}" width="{dims["width"]}" height="{dims["height"]}" class="{cls}" {"fetchpriority=\"high\" loading=\"eager\"" if priority else "loading=\"lazy\""} decoding="async">'

def btn(label, target, style='', symbol='arrow', service=None, context=''):
    attrs = f' data-book="{e(service)}" data-context="{e(context)}"' if service else ''
    return f'<a class="btn {style}" href="{e(link(target))}"{attrs}>{label}{icon(symbol) if symbol else ""}</a>'

def book(label='Выбрать дату', service='enduro', style='', context=''):
    return btn(label,'contacts/#contact',style,'arrow',service,context)

def brand():
    return f'<a class="brand" href="{link()}" aria-label="3030 — главная"><span class="brand-mark">3030<span class="brand-dot">.</span></span><span class="brand-text">Техника для жизни<br>Минск и область</span></a>'

def header(service):
    nav=[('enduro/','Эндуро','enduro'),('evacuator/','Эвакуатор','evacuator'),('limuzin/','Лимузины','limuzin'),('arenda-moto/','Мотоциклы','moto'),('contacts/','Контакты','contacts')]
    items=''.join(f'<a href="{link(p)}"{ " aria-current=\"page\"" if service==s else ""}>{t}</a>' for p,t,s in nav)
    return f'''<a class="skip-link" href="#main">Перейти к содержанию</a>
    <div class="topline"><div class="container"><span>МИНСК И МИНСКАЯ ОБЛАСТЬ · СВОЯ ТЕХНИКА</span><span class="topline-extra">Прокат 09:00–20:00 <span aria-hidden="true">&nbsp; / &nbsp;</span> Эвакуатор 24/7</span></div></div>
    <header class="header"><div class="container header-inner">{brand()}<nav class="nav" id="navigation" aria-label="Основная навигация">{items}</nav><div class="header-contact"><a class="header-phone" href="tel:{C['phone']}">{PHONE}</a><span>Позвоните — поможем выбрать</span></div><button class="menu-toggle js-only" aria-label="Открыть меню" aria-expanded="false" aria-controls="navigation">{icon('menu')}</button></div></header>'''

def footer(service):
    selected=service if service in ['enduro','evacuator','limuzin','moto'] else 'enduro'
    return f'''<footer class="footer"><div class="container"><div class="footer-grid"><div>{brand()}<p>Ближе к природе. В центре событий.<br>Рядом, когда нужна помощь.</p></div><div><div class="footer-title">Выберите направление</div><ul><li><a href="{link('enduro/')}">Прокат эндуро</a></li><li><a href="{link('evacuator/')}">Эвакуатор 24/7</a></li><li><a href="{link('limuzin/')}">Аренда лимузина</a></li><li><a href="{link('arenda-moto/')}">Дорожные мотоциклы</a></li></ul></div><div><div class="footer-title">Полезно знать</div><ul><li><a href="{link('enduro/s-instruktorom/')}">Эндуро для начинающих</a></li><li><a href="{link('enduro/na-den/')}">Аренда эндуро на день</a></li><li><a href="{link('evacuator/manipulyator/')}">Эвакуатор-манипулятор</a></li><li><a href="{link('contacts/')}">Контакты и реквизиты</a></li></ul></div><div><div class="footer-title">На связи</div><ul><li><a href="tel:{C['phone']}"><strong>{PHONE}</strong></a></li><li><a href="mailto:{C['email']}">{C['email']}</a></li><li><a href="{C['telegram']}" target="_blank" rel="noopener noreferrer" data-messenger="telegram">Telegram ↗</a> &nbsp; <a href="https://wa.me/375296701633" target="_blank" rel="noopener noreferrer" data-messenger="whatsapp">WhatsApp ↗</a></li></ul><p style="margin-top:16px">Прокат: ежедневно 09:00–20:00<br>Эвакуация: круглосуточно</p></div></div><div class="footer-bottom"><span>© 2026 3030. {C['legal_name']}. УНП {C['tax_id']}.</span><a href="{link('privacy/')}">Обработка данных</a><a href="{link('sitemap.xml')}">Карта сайта</a></div></div></footer>
    <div class="mobile-bar" aria-label="Быстрая связь">{btn('Позвонить','tel:'+C['phone'],'secondary','phone')}{book('Обсудить заказ',selected)}</div>'''

def dialogs():
    choices=''.join(f'<label><input type="radio" name="service" value="{s}" {"checked" if s=="enduro" else ""}><span>{label}</span></label>' for s,label in [('enduro','Эндуро'),('evacuator','Эвакуатор'),('limuzin','Лимузин'),('moto','Мотоцикл')])
    return f'''<dialog id="booking-dialog" class="dialog" aria-labelledby="booking-title"><button class="dialog-close" aria-label="Закрыть" data-close>{icon('close')}</button><p class="eyebrow">Напрямую владельцу</p><h2 id="booking-title">Давайте договоримся о поездке</h2><p class="dialog-intro">Выберите услугу и напишите нам. Уточним свободное время, детали и стоимость.</p><form id="booking-form"><fieldset class="form-services"><legend>Что вас интересует?</legend>{choices}</fieldset><p id="booking-context" class="small" hidden></p><div class="form-row"><div class="field"><label for="booking-name">Как к вам обращаться</label><input id="booking-name" name="name" autocomplete="given-name" maxlength="60" placeholder="Ваше имя"></div><div class="field"><label for="booking-date">Желаемая дата</label><input id="booking-date" type="date" name="date"></div></div><div class="field"><label for="booking-comment">Пожелания <span class="muted">(необязательно)</span></label><textarea id="booking-comment" name="comment" maxlength="1200" placeholder="Например: едем вдвоём, опыта пока нет"></textarea></div><p class="form-error" id="booking-error" role="alert" hidden></p><div class="form-submit"><button type="submit" name="channel" value="whatsapp" class="btn">В WhatsApp {icon('up')}</button><button type="submit" name="channel" value="telegram" class="btn secondary">В Telegram {icon('up')}</button></div><p class="form-help">Откроется чат с готовым текстом. Нажмите «Отправить» в мессенджере, чтобы мы получили запрос. Это обращение, а не подтверждённая бронь. <a href="{link('privacy/')}">Обработка данных</a>.</p><p id="booking-handoff" role="status" class="form-help" hidden></p><a id="booking-fallback" class="link small" target="_blank" rel="noopener noreferrer" hidden>Открыть чат вручную {icon('up')}</a></form><p class="form-help">Нужна помощь сейчас? <a href="tel:{C['phone']}">{PHONE}</a></p></dialog><dialog id="lightbox" class="dialog lightbox" aria-label="Просмотр фотографии"><button class="dialog-close" aria-label="Закрыть фотографию" data-close>{icon('close')}</button><img id="lightbox-img" alt="" width="1200" height="900"><p id="lightbox-caption"></p></dialog>'''

def crumbs(items):
    return '<nav class="breadcrumbs" aria-label="Хлебные крошки">'+f'<a href="{link()}">Главная</a>'+''.join(f'<span aria-hidden="true">/</span><a href="{link(path)}">{label}</a>' if path else f'<span aria-hidden="true">/</span><span aria-current="page">{label}</span>' for label,path in items)+'</nav>'

def cta(title='Хорошие поездки начинаются с разговора', text='Расскажите, что планируете. Поможем с техникой, датой и деталями.', service='enduro'):
    return f'<section class="section-sm"><div class="container cta-panel"><div><p class="eyebrow">На связи, чтобы помочь</p><h2>{title}</h2><p>{text}</p></div><div class="cta-actions"><a class="phone-large" href="tel:{C["phone"]}">{PHONE}</a><div class="actions">{book("Обсудить заказ",service)}{btn("Позвонить","tel:"+C["phone"],"secondary","phone")}</div></div></div></section>'

def feature_list(items):
    return '<ul class="feature-list">'+''.join(f'<li><span class="tick">{icon("check")}</span><div><strong>{title}</strong><p>{text}</p></div></li>' for title,text in items)+'</ul>'

def steps(items, title='Всё начинается с простого шага'):
    return f'<section class="section sage"><div class="container"><p class="eyebrow">Без лишних сложностей</p><h2>{title}</h2><div class="steps">'+''.join(f'<div class="step"><span class="step-index">0{i+1} /</span><div><h3>{title}</h3><p>{text}</p></div></div>' for i,(title,text) in enumerate(items))+'</div></div></section>'

def faq(items, title='Остались вопросы?'):
    return f'<section class="section" id="faq"><div class="container faq-layout"><div><p class="eyebrow">Ответы перед поездкой</p><h2>{title}</h2><p class="muted">Если ваш вопрос чуть сложнее —<br><a class="link" href="tel:{C["phone"]}">просто позвоните {icon("arrow")}</a></p></div><div class="faq">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)+'</div></div></section>'

def gallery(items, title='Не сток. Наши поездки.'):
    return f'<section class="section white" id="photos"><div class="container"><div class="section-head"><div><p class="eyebrow">Фотографии нашей техники</p><h2>{title}</h2></div><p>Техника, маршруты и моменты,<br>ради которых хочется повторить.</p></div><div class="gallery">'+''.join(f'<button type="button" data-gallery aria-label="Увеличить: {e(alt)}">{img(name,alt)}</button>' for name,alt in items)+'</div></div></section>'

def related(exclude=''):
    data=[('enduro','enduro/','bike','Эндуро за городом','Маршруты, инструктор и экипировка'),('evacuator','evacuator/','truck','Эвакуатор 24/7','Минск и Минская область'),('limuzin','limuzin/','car','Лимузин для события','С водителем, для вашей компании')]
    cards=''.join(f'<a class="related" href="{link(path)}">{icon(sym)}<div><h3>{title}</h3><p>{text}</p></div><span class="arrow">{icon("up")}</span></a>' for key,path,sym,title,text in data if key!=exclude)
    return f'<section class="section-sm"><div class="container"><p class="eyebrow">Другие направления 3030</p><div class="related-grid">{cards}</div></div></section>'

def page_hero(heading, intro, photo, alt, service, tag, chips, ticket, ticket_text, button='Выбрать дату', secondary='#prices', secondary_label='Смотреть цены', photo_pos=''):
    return f'''<section class="page-hero"><div class="container"><div class="hero-grid"><div class="hero-copy"><p class="eyebrow">{tag}</p><h1>{heading}</h1><p class="lead">{intro}</p><div class="hero-chips">{''.join(f'<span>{x}</span>' for x in chips)}</div><div class="actions">{book(button,service)}{btn(secondary_label,secondary,'secondary',None)}</div></div><div class="hero-photo" {f'style="{photo_pos}"' if photo_pos else ''}>{img(photo,alt,True)}<div class="photo-top"><span class="pill">{icon('pin')} Минск и область</span></div><div class="hero-ticket"><div><small>{ticket_text}</small><strong>{ticket}</strong></div><a class="circle-link" href="#prices" aria-label="Перейти к ценам">{icon('arrow')}</a></div></div></div></div></section>'''

def quick(items):
    return '<div class="container"><nav aria-label="Разделы страницы"><ul class="quick-nav">'+''.join(f'<li><a href="#{anchor}">{title}</a></li>' for anchor,title in items)+'</ul></nav></div>'

def table(headers, rows):
    return '<table class="price-table"><thead><tr>'+''.join(f'<th scope="col">{h}</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{c}</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table>'

def render(path,title,description,body,service='home',breadcrumb=None,service_name=None,offers=None,hero_image='',noindex=False):
    global CURRENT
    CURRENT=path
    content=body()
    canonical=absolute(path + '/' if path else '')
    breadcrumb=breadcrumb or []
    graph=[{'@type':'Organization','@id':absolute('#organization'),'name':C['name'],'legalName':C['legal_name'],'taxID':C['tax_id'],'url':absolute(),'telephone':C['phone'],'email':C['email'],'logo':absolute('assets/favicon.svg'),'sameAs':[C['telegram']]}, {'@type':'WebSite','@id':absolute('#website'),'url':absolute(),'name':'3030 — прокат и эвакуация в Минске','inLanguage':'ru-BY','publisher':{'@id':absolute('#organization')}}, {'@type':'WebPage','@id':canonical+'#webpage','url':canonical,'name':title,'description':description,'inLanguage':'ru-BY','isPartOf':{'@id':absolute('#website')},'dateModified':C['updated']}]
    graph.append({'@type':'SportsActivityLocation','@id':absolute('#enduro-location'),'name':'3030 — прокат эндуро в Лусково','url':absolute('enduro/'),'telephone':C['phone'],'image':absolute('assets/images/enduro-6.webp'),'parentOrganization':{'@id':absolute('#organization')},'address':{'@type':'PostalAddress','addressLocality':'Лусково','addressRegion':'Минская область, Минский район','addressCountry':'BY'},'openingHoursSpecification':{'@type':'OpeningHoursSpecification','dayOfWeek':['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],'opens':'09:00','closes':'20:00'}})
    if path and path!='404':
        items=[{'@type':'ListItem','position':1,'name':'Главная','item':absolute()}]
        items.extend({'@type':'ListItem','position':i+2,'name':name,'item':absolute(p)} for i,(name,p) in enumerate(breadcrumb))
        graph.append({'@type':'BreadcrumbList','@id':canonical+'#breadcrumb','itemListElement':items})
    if service_name:
        item={'@type':'Service','@id':canonical+'#service','name':service_name,'serviceType':service_name,'provider':{'@id':absolute('#organization')},'areaServed':[{'@type':'City','name':'Минск'},{'@type':'AdministrativeArea','name':'Минская область'}],'url':canonical}
        if hero_image:item['image']=absolute('assets/images/'+hero_image+'.webp')
        if offers:item['hasOfferCatalog']={'@type':'OfferCatalog','name':'Тарифы','itemListElement':[{'@type':'Offer','name':n,'price':str(p),'priceCurrency':'BYN','url':canonical+'#prices','description':d} for n,p,d in offers]}
        graph.append(item)
    robots='index,follow,max-image-preview:large' if INDEX and not noindex else 'noindex,follow'
    verification=''.join(f'<meta name="{name}" content="{e(C[key])}">' for key,name in [('google_verification','google-site-verification'),('yandex_verification','yandex-verification')] if C.get(key))
    data=json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('</','<\\/')
    html=f'''<!doctype html>
<html lang="ru" class="no-js"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(description)}"><meta name="robots" content="{robots}"><meta name="theme-color" content="#214d38"><meta name="format-detection" content="telephone=no"><link rel="canonical" href="{canonical}"><link rel="icon" href="{link('assets/favicon.svg')}" type="image/svg+xml"><link rel="apple-touch-icon" href="{link('assets/apple-touch-icon.png')}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="3030"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{absolute('assets/og-cover.jpg')}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="3030: эндуро, эвакуатор и лимузины в Минске"><meta name="twitter:card" content="summary_large_image">{verification}<link rel="preload" href="{link('assets/fonts/manrope-800.woff')}" as="font" type="font/woff" crossorigin><link rel="stylesheet" href="{link('assets/site.css')}"><script src="{link('assets/site.js')}" defer></script><script type="application/ld+json">{data}</script></head><body data-service="{service}" data-metrika="{e(C.get('metrika_id',''))}">{header(service)}<main id="main">{content}</main>{footer(service)}{dialogs()}</body></html>'''
    OUTPUT[(path+'/index.html') if path and path!='404' else ('404.html' if path=='404' else 'index.html')]=html
    if not noindex:PAGES.append((path,title,hero_image))

ENDURO_FAQ=[('Можно приехать без опыта?', 'Да. Для первой поездки выбирайте двухчасовой прокат с инструктором. Начинаем с подбора мотоцикла, экипировки и инструктажа; темп и маршрут подбираем под подготовку.'),('Что входит в стоимость?', 'Мотоцикл, полный бак и экипировка: шлем, защита тела, перчатки, мотоштаны, наколенники и мотоботы. В двухчасовой формат входит сопровождение инструктора.'),('Где начинается поездка?', 'База эндуро находится в Минском районе, в деревне Лусково. После согласования времени уточним точку встречи. Необходима предварительная запись.'),('Можно арендовать эндуро без инструктора?', 'Да, на 12 часов при наличии опыта: 180 BYN в будни и 200 BYN в выходные. Доставка при такой аренде — 50 BYN в радиусе 10 км от Минска. Условия и маршрут согласуем перед выдачей.'),('Что взять с собой?', 'Сменную одежду, питьевую воду и одежду по погоде. В прохладный день пригодится термобельё. Требования к документам и допуску уточните при записи.'),('Нужны ли права и какой минимальный возраст?', 'Условия допуска зависят от возраста, техники и согласованного маршрута. До бронирования сообщите возраст и опыт: подтвердим, какой формат вам подходит и какие документы нужны. Возможность езды по дорогам общего пользования нужно согласовать отдельно.')]

def enduro_rates():
    return f'''<section class="section white" id="prices"><div class="container prices-layout"><div><p class="eyebrow">Прокат эндуро в Минске</p><h2>Сначала формат.<br>Потом — приключение.</h2><p class="lead">Первый раз или уже уверенно в седле? Выбирайте поездку под свой опыт.</p><div class="segmented js-only" role="group" aria-label="Тарифы по дням недели"><button type="button" data-period="weekday" aria-pressed="true">Будни</button><button type="button" data-period="weekend" aria-pressed="false">Выходные</button></div><p class="small muted" id="rate-period" aria-live="polite">Тарифы на понедельник — пятницу</p><p class="price-note">Экипировка и полный бак включены.<br>Доставка при аренде на 12 часов: 50 BYN в радиусе 10 км от Минска.<br>Прицеп: 40 BYN в будни / 50 BYN в выходные.</p></div><div class="rate-cards"><article class="rate-card featured"><p class="eyebrow">Начать с удовольствием</p><h3>С инструктором</h3><p>2 часа · для знакомства с эндуро</p><div class="price"><span data-weekday="150" data-weekend="180">150</span> <small>BYN</small></div><p>Будни — 150 / выходные — 180 BYN</p><ul><li>Сопровождение инструктора</li><li>Подбор техники по росту и опыту</li><li>Комплект защиты и инструктаж</li></ul>{book('Хочу попробовать','enduro',context='2 часа с инструктором')}<a class="link small" style="margin-top:18px" href="{link('enduro/s-instruktorom/')}">Как проходит первая поездка {icon('up')}</a></article><article class="rate-card"><p class="eyebrow">Для опытных райдеров</p><h3>На целый день</h3><p>12 часов · без инструктора</p><div class="price"><span data-weekday="180" data-weekend="200">180</span> <small>BYN</small></div><p>Будни — 180 / выходные — 200 BYN</p><ul><li>При наличии опыта вождения</li><li>Экипировка и полный бак</li><li>Можно заказать доставку</li></ul>{book('Арендовать на день','enduro','secondary','12 часов без инструктора')}<a class="link small" style="margin-top:18px" href="{link('enduro/na-den/')}">Все условия аренды {icon('up')}</a></article></div></div></section>'''

def home():
    cards=[('enduro/','enduro-7','Эндуро на лесном маршруте в Минском районе','01 / НАВСТРЕЧУ ПРИРОДЕ','Прокат эндуро','Лесные маршруты, своя техника и инструктор рядом. Можно без опыта.','от 150 BYN / 2 часа'),('evacuator/','home-8','Эвакуатор с манипулятором перевозит автомобиль','02 / ПОМОЩЬ В ПУТИ','Эвакуатор 24/7','Перевезём автомобиль, мотоцикл или спецтехнику. Минск и область.','от 120 BYN'),('limuzin/','limuzin-14','Белый лимузин Chrysler 300C в Минске','03 / ОСОБЕННЫЙ ПОВОД','Аренда лимузина','Для свадьбы, дня рождения и вечера, который захочется запомнить.','от 150 BYN / час*')]
    return f'''<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Эндуро · Эвакуатор · Лимузины</p><h1>Ваш маршрут.<br>Ваши <em>эмоции.</em></h1><p class="lead">Выбирайтесь из города на эндуро. Отмечайте важное в лимузине. А если в пути нужна помощь — мы рядом.</p><div class="actions">{btn('Хочу на эндуро','enduro/')}{btn('Выбрать услугу','#services','secondary',None)}</div><div class="hero-proof"><span class="proof-icon">{icon('shield')}</span><div><strong>Своя техника. Живое общение.</strong><br>Работаем напрямую в Минске и области</div></div></div><div class="hero-photo">{img('enduro-6','Эндуро Regulmoto на лесном маршруте в Минском районе',True)}<div class="photo-top"><span class="pill">{icon('pin')} Лусково · Минский район</span><span class="pill">Можно без опыта</span></div><div class="hero-ticket"><div><small>Планы на ближайшие выходные</small><strong>2 часа. Лес. Полная перезагрузка.</strong></div><a class="circle-link" href="{link('enduro/')}" aria-label="Подробнее о прокате эндуро">{icon('up')}</a></div></div></div></section>
    <div class="container"><nav class="service-strip" aria-label="Быстрый выбор услуги"><a href="{link('enduro/')}"><span class="strip-icon">{icon('bike')}</span><span class="strip-text"><strong>За новыми ощущениями</strong><small>Эндуро с инструктором · от 150 BYN</small></span>{icon('up')}</a><a href="{link('evacuator/')}"><span class="strip-icon">{icon('truck')}</span><span class="strip-text"><strong>Нужна помощь на дороге</strong><small>Эвакуатор · круглосуточно</small></span>{icon('up')}</a><a href="{link('limuzin/')}"><span class="strip-icon">{icon('car')}</span><span class="strip-text"><strong>Планирую особенный день</strong><small>Лимузины · с водителем</small></span>{icon('up')}</a></nav></div>
    <section class="section" id="services"><div class="container"><div class="section-head"><div><p class="eyebrow">Три повода выбрать 3030</p><h2>Что у вас в планах?</h2></div><p>У каждого маршрута — своя история.<br>У нас — техника для вашей.</p></div><div class="cards">{''.join(f'<a class="service-card" href="{link(p)}"><div class="card-image">{img(photo,alt)}<span class="pill">{tag}</span></div><div class="card-body"><h3>{title}</h3><p>{text}</p><div class="card-foot"><strong>{price}</strong>{icon("up")}</div></div></a>' for p,photo,alt,tag,title,text,price in cards)}</div><p class="section-label">Больше нравится асфальт? <a class="link" href="{link('arenda-moto/')}">Есть и дорожные мотоциклы {icon('arrow')}</a></p><p class="price-note">* Chrysler 300C — 150 BYN/ч при аренде от 2 часов. Один час — 180 BYN.</p></div></section>
    <section class="section white"><div class="container split"><div class="split-photo">{img('enduro-7','Поездка на эндуро с инструктором по лесной тропе')}<div class="floating-note"><strong>Можно с нуля.</strong><span>Начнём с инструктажа.<br>Дальше — в вашем темпе.</span></div></div><div class="split-copy"><p class="eyebrow">Наш любимый способ отдохнуть</p><h2>Меньше города.<br>Больше настоящего.</h2><p class="lead">Шум леса, новые маршруты и приятная усталость. Чтобы попробовать эндуро, не нужно покупать мотоцикл или быть гонщиком.</p>{feature_list([('Всё необходимое уже здесь','Мотоцикл, полный бак и комплект экипировки включены.'),('Инструктор рядом','Поможет освоиться и подберёт маршрут по вашему уровню.'),('Недалеко от Минска','Стартуем из деревни Лусково. Выберите день — остальное обсудим.')])}{btn('Узнать больше об эндуро','enduro/')}</div></div></section>
    {steps([('Выберите, что хочется','Лесная поездка, красивый праздник или помощь с перевозкой.'),('Свяжитесь с нами','Уточним детали, свободное время и полную стоимость.'),('Встречаемся и начинаем','Согласуем точку встречи или подачу техники по адресу.')])}
    {cta()}{related('enduro')}'''

def enduro():
    models=[('enduro-1','REGULMOTO','250 см³','25 л.с.','120 кг'),('enduro-2','REGULMOTO Crosstrec','292 см³','28 л.с.','127 кг'),('enduro-3','PROGASI','300 см³','27 л.с.','117 кг')]
    return f'''<div class="container">{crumbs([('Прокат эндуро',None)])}</div>{page_hero('Прокат эндуро<br>в Минске','Поменяйте привычные выходные на лесные тропы. С инструктором для первого раза или на целый день — для тех, кто уже в седле.','enduro-7','Райдеры на лесном маршруте эндуро','enduro','За город — за впечатлениями',['Экипировка включена','Можно без опыта','Лусково'],'от 150 BYN / 2 часа','Поездка с инструктором')}{quick([('prices','Форматы и цены'),('bikes','Наши эндуро'),('included','Что включено'),('photos','Фотографии'),('faq','Вопросы')])}{enduro_rates()}
    <section class="section" id="bikes"><div class="container"><div class="section-head"><div><p class="eyebrow">Подберём под ваш рост и опыт</p><h2>Знакомьтесь: ваши эндуро</h2></div><p>Три модели 2025 года.<br>Наличие на дату уточним при записи.</p></div><div class="cards">{''.join(f'<article class="model-card"><div class="model-image">{img(photo,title+" — эндуро из нашего парка")}</div><div class="card-body"><h3>{title}</h3><div class="specs"><span>{cc}</span><span>{hp}</span><span>{weight}</span></div>{book("Узнать о мотоцикле","enduro","secondary",title)}</div></article>' for photo,title,cc,hp,weight in models)}</div></div></section>
    <section class="section white" id="included"><div class="container split"><div><p class="eyebrow">Приезжайте за эмоциями</p><h2>К поездке всё готово</h2>{feature_list([('Мотоцикл и топливо','Подготовленная техника, полный бак и подбор модели по росту и опыту.'),('Полный комплект защиты','Шлем, защита тела, перчатки, мотоштаны, наколенники и мотоботы.'),('Инструктаж и маршрут','Объясним управление и подберём сложность. В двухчасовом формате вас сопровождает инструктор.')])}{book('Запланировать поездку','enduro')}</div><div class="split-photo">{img('enduro-8','Два эндуро Regulmoto на маршруте в лесу')}<div class="floating-note"><strong>09:00–20:00</strong><span>Каждый день.<br>По предварительной записи.</span></div></div></div></section>
    {gallery([('enduro-5','Поездка на эндуро по пересечённой местности'),('enduro-12','Эндуро на лесной тропе'),('enduro-10','Остановка во время загородной поездки')],'Здесь начинается ваше приключение')}{faq(ENDURO_FAQ)}{cta('Пора выбраться из города','Напишите, когда хотите приехать и есть ли опыт. Подберём подходящий формат.','enduro')}{related('enduro')}'''

def enduro_instruction():
    return f'''<div class="container">{crumbs([('Эндуро','enduro/'),('С инструктором',None)])}</div>{page_hero('Эндуро впервые?<br>Начнём вместе.','Двухчасовая поездка с инструктором в Минском районе. Познакомимся с мотоциклом, подберём защиту и поедем в комфортном для вас темпе.','enduro-7','Группа на маршруте с инструктором','enduro','Эндуро для начинающих',['2 часа','Инструктор рядом','Защита включена'],'150 / 180 BYN','Будний / выходной день','Хочу попробовать')}
    <section class="section white" id="prices"><div class="container prices-layout"><div><p class="eyebrow">Понятный первый шаг</p><h2>Два часа с инструктором</h2><p class="lead">Формат для знакомства с техникой и активного отдыха. Сообщите свой опыт до поездки — подберём подходящий мотоцикл и маршрут.</p>{book('Выбрать время','enduro',context='Первая поездка, 2 часа с инструктором')}</div><div>{table(['Формат','Стоимость'],[['Понедельник — пятница<small>2 часа с сопровождением инструктора</small>','<strong>150 BYN</strong>'],['Суббота — воскресенье<small>2 часа с сопровождением инструктора</small>','<strong>180 BYN</strong>'],['Что включено<small>Мотоцикл, топливо, комплект защиты и инструктаж</small>','В тарифе']])}<p class="price-note">Точное время старта подтверждается при записи. Возраст, рост и условия допуска обсудим заранее.</p></div></div></section>
    {steps([('Подбираем экипировку','Шлем, защиту тела, перчатки, мотоштаны, наколенники и мотоботы — по размеру.'),('Знакомимся с управлением','Инструктор объяснит, как работают сцепление, тормоза и переключение передач.'),('Выезжаем на маршрут','Темп и сложность подбираются по подготовке. Если что-то непонятно, можно остановиться и спросить.')],'Как проходит первая поездка')}
    <section class="section"><div class="container editorial"><p class="eyebrow">До выезда</p><h2>Что взять и о чём предупредить</h2><p>Возьмите воду, сменную одежду и вещи по погоде. Защитную экипировку выдаём на месте. В холодный день удобно надеть термобельё; после маршрута может понадобиться сухой комплект одежды.</p><p>При записи расскажите о своём опыте: ездили ли вы на мотоцикле, знакомы ли со сцеплением и переключением передач. Сообщите возраст и рост — это поможет подобрать технику и подтвердить условия допуска. Не планируйте самостоятельный выезд на дороги общего пользования без согласования.</p><h2>Где встречаемся</h2><p>База находится в деревне Лусково, Минский район. Сначала согласуйте время, затем уточните точку встречи. Прокат работает ежедневно с 09:00 до 20:00, по предварительной записи.</p><a class="link" href="{link('contacts/')}">Адреса и контакты {icon('arrow')}</a></div></section>{faq(ENDURO_FAQ[:3])}{cta('Первый раз бывает только однажды','Сделаем его понятным и запоминающимся. Напишите, какой день вам подходит.','enduro')}<section class="section-sm"><div class="container"><a class="link" href="{link('enduro/')}">Все мотоциклы и форматы эндуро {icon('arrow')}</a></div></section>'''

def enduro_day():
    return f'''<div class="container">{crumbs([('Эндуро','enduro/'),('Аренда на день',None)])}</div>{page_hero('Ваш эндуро.<br>На целый день.','12 часов без инструктора для райдеров с опытом. Подготовленный мотоцикл, экипировка и возможность доставки к месту катания.','enduro-10','Эндуро на фоне полей Минского района','enduro','Аренда эндуро на 12 часов',['Для опытных','Полный бак','Доставка по согласованию'],'от 180 BYN / 12 часов','Будний день','Обсудить аренду')}
    <section class="section white" id="prices"><div class="container prices-layout"><div><p class="eyebrow">Стоимость и логистика</p><h2>День в вашем ритме</h2><p class="lead">Выбирайте дату и расскажите, где планируете кататься. Условия выдачи, возврата и доставки согласуем до бронирования.</p>{book('Арендовать на 12 часов','enduro',context='12 часов без инструктора')}</div><div>{table(['Услуга','Будни','Выходные'],[['12 часов без инструктора<small>При наличии опыта вождения</small>','<strong>180 BYN</strong>','<strong>200 BYN</strong>'],['Доставка<small>При аренде на 12 часов, радиус 10 км от Минска</small>','50 BYN','50 BYN'],['Аренда прицепа','40 BYN','50 BYN']])}<p class="price-note">Доставка и прицеп оплачиваются отдельно. Точный адрес и время передачи техники согласуются заранее.</p></div></div></section>
    <section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Чтобы поездка прошла спокойно</p><h2>Обсудим до старта</h2></div></div><div class="info-grid"><article class="info-card">{icon('bike')}<h3>Опыт и модель</h3><p>Расскажите, на какой технике ездили. Подберём эндуро по росту и подготовке, подтвердим наличие на дату.</p></article><article class="info-card">{icon('route')}<h3>Место и маршрут</h3><p>Согласуйте район катания и условия использования техники. Уточните требования к документам и допуску.</p></article><article class="info-card">{icon('clock')}<h3>Выдача и возврат</h3><p>Заранее договоримся о времени, месте, доставке и состоянии техники при возврате.</p></article></div></div></section>
    {steps([('Свяжитесь с нами','Сообщите дату, опыт вождения и желаемую модель.'),('Согласуйте условия','Уточним документы, выдачу, возврат и доставку при необходимости.'),('Заберите эндуро','Осмотрите технику вместе с нами и получите экипировку.')],'Как арендовать эндуро на день')}{faq([ENDURO_FAQ[3],ENDURO_FAQ[1],('А если опыта ещё нет?',f'Начните с <a class="link" href="{link("enduro/s-instruktorom/")}">двухчасовой поездки с инструктором</a>. Она стоит 150 BYN в будни и 180 BYN в выходные.')])}{cta('День на эндуро уже в планах?','Осталось выбрать дату и согласовать технику.','enduro')}'''

TOW_ROWS=[['Мотоцикл или легковой автомобиль','от 120 BYN'],['Внедорожник, S-класс или минивэн','от 140 BYN'],['Микроавтобус<small>Короткая / средняя база</small>','от 150 BYN'],['Микроавтобус<small>Макси-база</small>','от 200 BYN'],['Эвакуатор с манипулятором','от 250 BYN'],['Извлечение из кювета, грязи или сугроба','от 200 BYN']]
TOW_FAQ=[('От чего зависит итоговая цена?', 'От типа и размеров транспорта, адресов погрузки и доставки, состояния колёс и сложности погрузки. Сообщите эти детали по телефону — стоимость согласуем до выезда.'),('Можно погрузить авто с заблокированными колёсами?', 'Да, для таких ситуаций подбираем манипулятор или подкатные тележки. Тариф на тележки — дополнительно 50 BYN за колесо. Нужный способ зависит от положения и состояния автомобиля.'),('Выезжаете ночью и за МКАД?', 'Да. Выезд после 23:00 — плюс 20% к стоимости. За МКАД: эвакуатор с лебёдкой — 1,5 BYN/км, с манипулятором — 3 BYN/км. Маршрут и итоговую сумму уточняйте перед заказом.'),('Работаете с организациями и страховыми случаями?', 'Да, работаем с физическими и юридическими лицами, предоставляем документы для подтверждения расходов, в том числе при ДТП. Безналичный расчёт — от +20% к стоимости; условия согласуются при заказе.'),('Как быстро приедет эвакуатор?', 'Время зависит от вашего адреса, дорожной обстановки и доступности техники. Назовём реальное время подачи при звонке.')]

def tow():
    return f'''<div class="container">{crumbs([('Эвакуатор в Минске',None)])}</div>{page_hero('Эвакуатор в Минске.<br>Помощь, которая рядом.','Автомобиль не едет? Перевезём его на СТО, стоянку или по нужному адресу. Работаем с мототехникой, легковыми авто и микроавтобусами — круглосуточно.','home-8','Перевозка автомобиля эвакуатором с краном-манипулятором','evacuator','На дороге не остаётесь одни',['24/7','Минск и область','Документы для страховой'],'от 120 BYN','Эвакуация легкового автомобиля','Рассчитать стоимость', 'tel:'+C['phone'],'Позвонить сейчас')}{quick([('prices','Цены'),('fleet','Техника'),('business','Для организаций'),('photos','Фото работ'),('faq','Вопросы')])}
    <section class="section white" id="prices"><div class="container prices-layout"><div><p class="eyebrow">Сначала согласуем цену</p><h2>Сколько стоит эвакуатор</h2><p class="lead">Расскажите, что случилось, где стоит автомобиль и куда его нужно перевезти. Подберём технику под вашу ситуацию.</p>{btn('Вызвать эвакуатор','tel:'+C['phone'],'','phone')}<p class="price-note">Цены «от» — базовые. Итог зависит от маршрута и сложности погрузки.</p></div><div>{table(['Перевозка','Стоимость'],TOW_ROWS)}<details class="price-note"><summary class="link">Доплаты и дополнительные услуги</summary>{table(['Условие / услуга','Тариф'],[['Лебёдка: выезд за МКАД','1,5 BYN/км'],['Манипулятор: выезд за МКАД','3 BYN/км'],['Выезд после 23:00','+20%'],['Подкатная тележка','50 BYN/колесо'],['Простой по вине заказчика','60 BYN / 30 мин'],['Сверка номеров (туда и обратно)','от 220 BYN'],['Запуск двигателя 12 В / 24 В','от 60 / 120 BYN'],['Подвоз топлива','от 90 BYN'],['Безналичный расчёт','от +20%']])}</details></div></div></section>
    <section class="section" id="fleet"><div class="container"><div class="section-head"><div><p class="eyebrow">Под разные задачи</p><h2>Подберём нужный эвакуатор</h2></div></div><div class="cards"><article class="model-card limo"><div class="model-image">{img('evacuator-7','Эвакуатор Ford с лебёдкой')}</div><div class="card-body"><h3>С лебёдкой</h3><div class="specs"><span>До 3 тонн</span><span>Платформа 4,8 × 2,2 м</span></div><p>Для легковых авто, мотоциклов и транспорта, который можно поднять на платформу.</p>{book('Узнать стоимость','evacuator','secondary','Эвакуатор с лебёдкой')}</div></article><article class="model-card limo"><div class="model-image">{img('home-8','Эвакуатор с манипулятором и автомобилем на платформе')}</div><div class="card-body"><h3>С манипулятором</h3><div class="specs"><span>Шасси до 5 т</span><span>Стрела до 9 м</span></div><p>Когда колёса или руль заблокированы, а обычная погрузка затруднена.</p>{btn('Подробнее о манипуляторе','evacuator/manipulyator/','secondary')}</div></article><article class="model-card limo"><div class="model-image">{img('evacuator-19','Строительный манипулятор при перевозке груза')}</div><div class="card-body"><h3>Для тяжёлых грузов</h3><div class="specs"><span>Шасси до 18 т</span><span>Кран до 8 т</span></div><p>Стройматериалы, оборудование и спецтехника. От 100 BYN/ч, минимум 3 часа + час подачи.</p>{book('Обсудить перевозку','evacuator','secondary','Строительный манипулятор')}</div></article></div></div></section>
    {steps([('Позвоните и назовите адрес','Сообщите марку авто, неисправность и состояние колёс. При необходимости отправьте фото.'),('Согласуйте подачу и цену','Подберём эвакуатор, уточним время приезда и стоимость маршрута.'),('Доставим и оформим документы','Погрузим транспорт, отвезём по нужному адресу и выдадим документы.')],'Как вызвать эвакуатор')}
    <section class="section white" id="business"><div class="container split"><div><p class="eyebrow">Физическим и юридическим лицам</p><h2>Перевозка с документами</h2><p class="lead">Работаем с частными клиентами и организациями. Перевозим автомобили на СТО и стоянки, технику и оборудование — по согласованному маршруту.</p>{feature_list([('Подтверждение расходов','Предоставляем документы, в том числе для страховых случаев при ДТП.'),('Безналичная оплата','Условия расчёта согласуем до заказа. Доплата — от 20% к стоимости.')])}{book('Обсудить задачу','evacuator')}</div><div class="split-photo" style="height:410px">{img('evacuator-21','Эвакуатор доставляет легковой автомобиль')}</div></div></section>
    {gallery([('evacuator-17','Работа крана-манипулятора на выезде'),('evacuator-18','Погрузка автомобиля с повреждениями'),('evacuator-25','Перевозка груза манипулятором')],'Техника в работе')}{faq(TOW_FAQ)}{cta('Нужен эвакуатор сейчас?','Позвоните: уточним адрес, состояние автомобиля, стоимость и время подачи.','evacuator')}{related('evacuator')}'''

def manipulator():
    return f'''<div class="container">{crumbs([('Эвакуатор','evacuator/'),('Манипулятор',None)])}</div>{page_hero('Эвакуатор<br>с манипулятором','Поможем, когда обычной лебёдки недостаточно: заблокированы колёса или руль, автомобиль повреждён или находится в неудобном для погрузки месте.','home-8','Эвакуатор с манипулятором перевозит легковой автомобиль','evacuator','Минск и Минская область · 24/7',['Шасси до 5 тонн','Кран до 4 тонн','Вылет до 9 м'],'от 250 BYN','Погрузка и перевозка','Обсудить погрузку','tel:'+C['phone'],'Вызвать сейчас')}
    <section class="section white" id="prices"><div class="container prices-layout"><div><p class="eyebrow">С учётом вашей ситуации</p><h2>Стоимость и возможности</h2><p class="lead">Чтобы выбрать подходящий способ погрузки, отправьте фото автомобиля и пространства вокруг него. Уточним доступ, массу и состояние машины.</p>{book('Уточнить стоимость','evacuator',context='Эвакуатор с манипулятором')}</div><div>{table(['Параметр / услуга','Значение'],[['Эвакуатор с манипулятором','от 250 BYN'],['Выезд за МКАД','3 BYN/км'],['Грузоподъёмность шасси','до 5 тонн'],['Грузоподъёмность крана','до 4 тонн'],['Вылет стрелы','до 9 метров'],['Размер кузова','5,5 × 2,3 м']])}<p class="price-note">Максимальная грузоподъёмность крана зависит от вылета стрелы и условий работы. Возможность конкретной погрузки подтверждаем перед выездом. Ночной выезд после 23:00 — +20%.</p></div></div></section>
    <section class="section"><div class="container"><p class="eyebrow">Когда нужен кран</p><h2>Сложная погрузка — обсудим решение</h2><div class="info-grid"><article class="info-card">{icon('car')}<h3>Заблокированы колёса</h3><p>Если автомобиль не катится или повреждена подвеска, подберём способ подъёма с учётом состояния машины.</p></article><article class="info-card">{icon('pin')}<h3>Неудобное положение</h3><p>Автомобиль стоит на тесной парковке или в труднодоступном месте. Проверим пространство для техники и стрелы.</p></article><article class="info-card">{icon('truck')}<h3>Техника и груз</h3><p>Поможем с перевозкой оборудования и спецтехники. Для более тяжёлых задач доступен строительный манипулятор.</p></article></div></div></section>
    <section class="section sage"><div class="container editorial"><h2>Что сообщить при заказе</h2><p>Назовите адрес погрузки и доставки, марку и примерную массу автомобиля, состояние колёс и рулевого управления. Расскажите об ограничениях по высоте, подъезде и свободном месте рядом с машиной.</p><p>Фото или короткое видео помогут оценить задачу точнее. Стоимость, возможность погрузки и время приезда согласуем до выезда. Если заказ оформляется на организацию или нужен документ для страховой, сообщите об этом сразу.</p><a class="link" href="{link('evacuator/#prices')}">Все тарифы и доплаты на эвакуацию {icon('arrow')}</a></div></section>{faq([TOW_FAQ[0],TOW_FAQ[2],TOW_FAQ[3]])}{cta('Опишите ситуацию — подберём технику','Нужен манипулятор или хватит обычного эвакуатора? Поможем разобраться по телефону.','evacuator')}'''

LIMO_FAQ=[('Сколько человек помещается в лимузин?', 'Chrysler 300C рассчитан на компанию до 12 человек, Hummer H2 и Cadillac Escalade — до 25. Сообщите число гостей: подтвердим комфортный вариант и доступность автомобиля.'),('Почему указана цена от 150 BYN в час?', 'Это тариф Chrysler 300C при заказе от двух часов. Один час стоит 180 BYN. Hummer H2 и Cadillac Escalade: один час — 250 BYN, от двух часов — 210 BYN/ч.'),('Можно заказать на свадьбу, выпускной или день рождения?', 'Да. Согласуем дату, время, маршрут, остановки и количество гостей. Машину с водителем подаём по предварительно согласованному адресу.'),('Когда бронирование считается подтверждённым?', 'Когда мы проверили доступность машины на выбранную дату и согласовали с вами все условия. Сообщение в мессенджере само по себе не подтверждает бронь.'),('Можно заказать фотографа?', 'На сайте указан вариант с фотографом за дополнительные 50 BYN. Доступность, продолжительность и условия съёмки уточняйте при бронировании.')]

def limo():
    models=[('limuzin-3','Chrysler 300C','до 12 гостей','180','150','Свадьба, свидание или камерный праздник.'),('limuzin-5','Hummer H2','до 25 гостей','250','210','Для большой компании и яркого появления.'),('limuzin-8','Cadillac Escalade','до 25 гостей','250','210','Просторный салон для праздника в пути.')]
    return f'''<div class="container">{crumbs([('Аренда лимузина',None)])}</div>{page_hero('Особенный день.<br>Красивое начало.','Аренда лимузина в Минске с водителем. Соберите близких, выберите маршрут и наслаждайтесь праздником — о дороге позаботимся мы.','limuzin-14','Белый лимузин Chrysler 300C у театра в Минске','limuzin','Для моментов, которые запоминают',['С водителем','До 25 гостей','Подача по адресу'],'от 150 BYN / час','Chrysler 300C · при заказе от 2 часов','Узнать свободные даты')}{quick([('prices','Лимузины и цены'),('occasions','Для вашего события'),('photos','Фотографии'),('faq','Вопросы')])}
    <section class="section white" id="prices"><div class="container"><div class="section-head"><div><p class="eyebrow">Выберите свою атмосферу</p><h2>Три лимузина. Ваш повод.</h2></div><p>Стоимость зависит от модели и длительности. Дату и маршрут согласуем лично.</p></div><div class="cards">{''.join(f'<article class="model-card limo"><div class="model-image">{img(photo,title+" — "+("салон лимузина" if title=="Cadillac Escalade" else "лимузин в Минске"))}</div><div class="card-body"><h3>{title}</h3><div class="specs"><span>{guests}</span><span>С водителем</span></div><p>{text}</p><div class="model-price">{hour} BYN <span class="small muted">/ 1 час</span></div><div class="price-meta">От 2 часов — {long} BYN/ч</div>{book("Узнать свободную дату","limuzin","secondary",title)}</div></article>' for photo,title,guests,hour,long,text in models)}</div><p class="price-note">Фотограф — дополнительно 50 BYN; доступность и условия уточняйте. Модель, длительность, адрес подачи и маршрут подтверждаем при заказе.</p></div></section>
    <section class="section" id="occasions"><div class="container split"><div class="split-photo">{img('limuzin-4','Салон лимузина с баром и подсветкой')}<div class="floating-note"><strong>Ваш праздник.</strong><span>Водитель за рулём.<br>Вы — в центре событий.</span></div></div><div><p class="eyebrow">Не просто доехать</p><h2>Праздник начинается<br>ещё в пути</h2>{feature_list([('Свадьба и фотосессия','Согласуем подачу, маршрут и остановки, чтобы всё вписалось в ваш день.'),('День рождения и встреча друзей','Просторный салон, музыка и компания близких — без забот о дороге.'),('Выпускной или корпоратив','Подберём автомобиль по числу гостей и уточним детали поездки.')])}{book('Обсудить мой праздник','limuzin')}</div></div></section>
    {steps([('Расскажите о событии','Дата, количество гостей, время начала и желаемый лимузин.'),('Согласуем маршрут','Адрес подачи, остановки, длительность и итоговая стоимость.'),('Встречайте водителя','Лимузин будет подан в согласованное место и время.')],'Организовать поездку проще, чем кажется')}{gallery([('limuzin-10','Лимузин Chrysler 300C у Большого театра'),('limuzin-6','Салон лимузина Hummer H2'),('limuzin-18','Вечерняя поездка на лимузине по городу')],'Снаружи красиво. Внутри — праздник.')}{faq(LIMO_FAQ)}{cta('Уже есть дата и повод?','Проверим свободные лимузины и поможем спланировать поездку.','limuzin')}{related('limuzin')}'''

def moto():
    rows=[['Honda CBR 600F3','180 BYN','220 BYN'],['Honda CBR 600F4','200 BYN','230 BYN'],['Yamaha YZF 600 R6','190 BYN','230 BYN'],['Kawasaki ZX-6R 636','200 BYN','240 BYN'],['Ducati 848 EVO Corse','300 BYN','350 BYN'],['Honda CB 600 F Hornet','190 BYN','230 BYN'],['Suzuki SV 650 N','180 BYN','220 BYN']]
    return f'''<div class="container">{crumbs([('Дорожные мотоциклы',None)])}</div><section class="section-sm"><div class="container"><p class="eyebrow">Прокат дорожных мотоциклов в Минске</p><h1>Город. Дорога.<br>И ваш мотоцикл.</h1><p class="lead">Honda, Yamaha, Kawasaki, Ducati и Suzuki в аренду на сутки. Подберите модель для городских поездок или знакомства с новым классом техники.</p><div class="actions">{book('Выбрать мотоцикл','moto')}{btn('Тарифы и модели','#prices','secondary',None)}</div></div></section>
    <section class="section white" id="prices"><div class="container prices-layout"><div><p class="eyebrow">Наш мотопарк</p><h2>Модели и стоимость суток</h2><p class="lead">Базовая экипировка включена. Выдача — в Минске, ул. Короля, 75, по предварительной записи.</p><p class="small muted">Прокат работает ежедневно, 09:00–20:00.</p>{book('Уточнить наличие','moto')}</div><div>{table(['Модель','Пн–чт','Пт–вс'],rows)}<p class="price-note">Аренда с водителем: 100 BYN за 30 минут. Наличие модели на дату и условия поездки уточняйте.</p></div></div></section><section class="section"><div class="container"><p class="eyebrow">До бронирования</p><h2>Условия аренды</h2><div class="info-grid"><article class="info-card">{icon('shield')}<h3>Документы</h3><p>От 18 лет. Оригиналы паспорта и водительского удостоверения категории A. Перед выдачей оформляется договор и осмотр техники.</p></article><article class="info-card">{icon('route')}<h3>Пробег</h3><p>В сутки включено 200 км. За каждые дополнительные 10 км — 3 BYN. Во время аренды обязательно соблюдение ПДД.</p></article><article class="info-card">{icon('bike')}<h3>Техника и защита</h3><p>Выдаём с полным баком; вернуть нужно также с полным баком. Включены шлем и перчатки, доступны защита тела и наколенники.</p></article></div></div></section>{steps([('Выберите модель','Сообщите дату и опыт вождения — подтвердим доступность.'),('Приезжайте с документами','Заключим договор и осмотрим мотоцикл вместе с вами.'),('Возвращайте по договорённости','Согласуем время возврата. Бак должен быть полным.')],'Как арендовать дорожный мотоцикл')}{cta('Какой мотоцикл хотите попробовать?','Назовите модель и дату — подскажем доступные варианты.','moto')}{related('enduro')}'''

def contacts():
    return f'''<div class="container">{crumbs([('Контакты',None)])}</div><section class="section-sm"><div class="container"><p class="eyebrow">3030 · Минск и область</p><h1>Давайте на связи.</h1><p class="lead">Поможем выбрать технику, согласовать время и разобраться в деталях.</p></div></section><section class="section-sm" id="contact"><div class="container contact-grid"><div class="contact-primary"><p class="eyebrow">Звоните или пишите</p><a class="phone-large" href="tel:{C['phone']}">{PHONE}</a><p class="muted small">Прокат: ежедневно с 09:00 до 20:00.<br>Эвакуатор: круглосуточно.</p><div class="actions"><a class="btn" href="{C['telegram']}" target="_blank" rel="noopener noreferrer" data-messenger="telegram">Telegram {icon('up')}</a><a class="btn secondary" href="https://wa.me/375296701633" target="_blank" rel="noopener noreferrer" data-messenger="whatsapp">WhatsApp {icon('up')}</a></div><div class="contact-block"><h3>Удобнее по почте?</h3><a class="link" href="mailto:{C['email']}">{C['email']} {icon('up')}</a></div><div class="contact-block"><p>Перед приездом обязательно согласуйте время и место встречи.</p>{book('Обсудить заказ','enduro')}</div></div><div><div class="contact-block" style="margin-top:0;padding-top:0;border:0"><p class="eyebrow">01 / Прокат эндуро</p><h3>Минский район, д. Лусково</h3><p>Точку старта уточним после записи. Не приезжайте без согласования: группа может находиться на маршруте.</p><a class="link" href="https://yandex.by/maps/?text=%D0%9B%D1%83%D1%81%D0%BA%D0%BE%D0%B2%D0%BE%2C%20%D0%9C%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9%20%D1%80%D0%B0%D0%B9%D0%BE%D0%BD" target="_blank" rel="noopener noreferrer">Посмотреть деревню на карте {icon('up')}</a></div><div class="contact-block"><p class="eyebrow">02 / Дорожные мотоциклы</p><h3>Минск, ул. Короля, 75</h3><p>Выдача и возврат по предварительной договорённости.</p><a class="link" href="https://yandex.by/maps/?text=%D0%9C%D0%B8%D0%BD%D1%81%D0%BA%2C%20%D0%9A%D0%BE%D1%80%D0%BE%D0%BB%D1%8F%2075" target="_blank" rel="noopener noreferrer">Показать на карте {icon('up')}</a></div><div class="contact-block"><p class="eyebrow">03 / Эвакуатор и лимузины</p><h3>Подача по согласованному адресу</h3><p>Сообщите адрес, дату и время. Для эвакуатора дополнительно уточним состояние и размеры автомобиля.</p></div></div></div></section><section class="section white"><div class="container"><p class="eyebrow">Официальная информация</p><h2>Реквизиты</h2><div class="legal"><p><strong>{C['legal_name']}</strong><br>УНП {C['tax_id']}<br>Свидетельство о государственной регистрации № {C['tax_id']}, выдано Минским горисполкомом.</p><p>Телефон: <a href="tel:{C['phone']}">{PHONE}</a><br>Электронная почта: <a href="mailto:{C['email']}">{C['email']}</a></p></div></div></section>{related('enduro')}'''

def privacy():
    return f'''<div class="container">{crumbs([('Обработка данных',None)])}</div><section class="section-sm"><div class="container legal"><p class="eyebrow">Информация для посетителей</p><h1>Обработка данных<br>при обращении</h1><p>Дата обновления: 5 октября 2026 года.</p><h2>Кому вы обращаетесь</h2><p>{C['legal_name']}, УНП {C['tax_id']}. По вопросам обработки информации можно написать на <a href="mailto:{C['email']}">{C['email']}</a> или позвонить по номеру {PHONE}.</p><h2>Как работает форма на сайте</h2><p>Форма помогает составить текст обращения: выбранная услуга, имя, желаемая дата и комментарий. Поля необязательны. Эти данные не отправляются на сервер сайта и не сохраняются в локальном хранилище браузера. После нажатия кнопки открывается сторонний мессенджер с подготовленным текстом.</p><p>Мы получим запрос только после того, как вы самостоятельно отправите сообщение в чате. Не указывайте в форме паспортные данные, платёжные реквизиты и другую информацию, которая не нужна для первого обращения.</p><h2>Для чего нужна информация</h2><p>Информация из отправленного сообщения используется, чтобы ответить на ваш вопрос, уточнить доступность техники, рассчитать стоимость и согласовать условия услуги. Порядок и срок хранения переписки, исправление или удаление сведений можно уточнить по указанным контактам.</p><h2>Сторонние сервисы</h2><p>При переходе в Telegram, WhatsApp, почтовое приложение или на карты действуют условия соответствующего сервиса. Адрес страницы при переходе может передаваться стороннему сервису в соответствии с настройками браузера.</p><h2>Технические данные</h2><p>Хостинг может обрабатывать технические сведения о запросах: IP-адрес, время обращения, адрес страницы и сведения о браузере. В текущей версии сайта внешние системы аналитики не подключены, рекламные cookie не устанавливаются. Фотографии и шрифты загружаются с сайта.</p><h2>Как связаться</h2><p>Если вы хотите уточнить, исправить или удалить сведения из обращения, напишите на <a class="link" href="mailto:{C['email']}">{C['email']}</a>. Укажите, какое обращение вы имеете в виду; не отправляйте лишние персональные данные.</p></div></section>'''

def notfound():
    return f'<section class="section"><div class="container"><p class="eyebrow">404 · Немного не тот маршрут</p><h1>Этой страницы нет.<br>Но путь найдётся.</h1><p class="lead">Возможно, ссылка устарела. Выберите направление или вернитесь на главную.</p><div class="actions">{btn("На главную","")}{btn("Прокат эндуро","enduro/","secondary")}{btn("Эвакуатор","evacuator/","secondary")}</div></div></section>'

render('', '3030 — прокат эндуро, эвакуатор и лимузины в Минске', 'Эндуро с инструктором от 150 BYN, эвакуатор 24/7 и лимузины с водителем. Свой парк, реальные фотографии и понятные тарифы. Минск и Минская область.', home, hero_image='enduro-6')
render('enduro','Прокат эндуро в Минске от 150 BYN — с инструктором | 3030','Аренда эндуро в Лусково: 2 часа с инструктором от 150 BYN или 12 часов от 180 BYN. Экипировка и топливо включены. Regulmoto и Progasi. Запись по телефону.',enduro,'enduro',[('Прокат эндуро','enduro/')],'Прокат эндуро в Минске',[('2 часа с инструктором',150,'Будни; в выходные — 180 BYN'),('12 часов без инструктора',180,'Будни, при наличии опыта; выходные — 200 BYN')],'enduro-7')
render('enduro/s-instruktorom','Эндуро с инструктором в Минске — для начинающих | 3030','Первая поездка на эндуро: инструктаж, подбор техники, экипировка и сопровождение. 2 часа: 150 BYN в будни, 180 BYN в выходные. База в Лусково.',enduro_instruction,'enduro',[('Эндуро','enduro/'),('С инструктором','enduro/s-instruktorom/')],'Прокат эндуро с инструктором',[('2 часа с инструктором',150,'Понедельник — пятница, выходные — 180 BYN')],'enduro-7')
render('enduro/na-den','Аренда эндуро на день в Минске — 12 часов от 180 BYN | 3030','Эндуро без инструктора на 12 часов для опытных райдеров: 180 BYN в будни, 200 BYN в выходные. Доставка от Минска, экипировка, аренда прицепа.',enduro_day,'enduro',[('Эндуро','enduro/'),('На день','enduro/na-den/')],'Аренда эндуро на 12 часов',[('12 часов без инструктора',180,'При наличии опыта. Будни — 180 BYN, выходные — 200 BYN')],'enduro-10')
render('evacuator','Эвакуатор в Минске 24/7 от 120 BYN — манипулятор | 3030','Вызвать эвакуатор в Минске и области: легковые авто от 120 BYN, манипулятор от 250 BYN. Круглосуточно. Документы для страховой и юридических лиц.',tow,'evacuator',[('Эвакуатор','evacuator/')],'Услуги эвакуатора в Минске',[('Эвакуация легкового автомобиля',120,'Базовая стоимость; маршрут и дополнительные работы рассчитываются отдельно'),('Эвакуатор с манипулятором',250,'Базовая стоимость; итог согласуется до выезда')],'home-8')
render('evacuator/manipulyator','Эвакуатор с манипулятором в Минске от 250 BYN | 3030','Эвакуация с манипулятором: заблокированные колёса, повреждённые авто, техника. Шасси до 5 т, кран до 4 т. Минск и область, выезд 24/7.',manipulator,'evacuator',[('Эвакуатор','evacuator/'),('Манипулятор','evacuator/manipulyator/')],'Эвакуатор с манипулятором',[('Эвакуатор с манипулятором',250,'Базовая стоимость, за МКАД — 3 BYN/км')],'home-8')
render('limuzin','Аренда лимузина в Минске с водителем — цены | 3030','Chrysler 300C, Hummer H2 и Cadillac Escalade: лимузины до 25 мест для свадьбы и праздника. Chrysler от 150 BYN/ч при заказе от 2 часов.',limo,'limuzin',[('Лимузины','limuzin/')],'Аренда лимузина в Минске',[('Chrysler 300C на 1 час',180,'От 2 часов — 150 BYN/ч'),('Hummer H2 на 1 час',250,'От 2 часов — 210 BYN/ч'),('Cadillac Escalade на 1 час',250,'От 2 часов — 210 BYN/ч')],'limuzin-14')
render('arenda-moto','Прокат мотоциклов в Минске от 180 BYN в сутки | 3030','Аренда дорожных мотоциклов: Honda, Yamaha, Kawasaki, Ducati, Suzuki. Экипировка включена. Тарифы от 180 BYN/сутки. Минск, ул. Короля, 75.',moto,'moto',[('Мотоциклы','arenda-moto/')],'Прокат дорожных мотоциклов')
render('contacts','Контакты 3030 — прокат и эвакуатор в Минске','Телефон +375 29 670-16-33, Telegram и WhatsApp. Эндуро — Лусково; дорожные мотоциклы — Короля, 75. Контакты и реквизиты ИП Гайшунова В. С.',contacts,'contacts',[('Контакты','contacts/')])
render('privacy','Обработка данных при обращении — 3030','Как работает форма обращения на сайте 3030, какие данные используются и как связаться по вопросам обработки информации.',privacy,'privacy',[('Обработка данных','privacy/')],noindex=True)
# 404 uses absolute deployment-root paths so unknown nested URLs have working assets/navigation.
CURRENT=''
render('404','Страница не найдена — 3030','Страница не найдена. Прокат эндуро, лимузинов и услуги эвакуатора в Минске.',notfound,'home',noindex=True)
OUTPUT['404.html']=OUTPUT['404.html'].replace('href="../','href="'+urlparse(SITE).path.rstrip('/')+'/').replace('src="../','src="'+urlparse(SITE).path.rstrip('/')+'/')
def sitemap_entry(path, photo):
    image_xml=f'<image:image><image:loc>{e(absolute("assets/images/"+photo+".webp"))}</image:loc></image:image>' if photo else ''
    return f'<url><loc>{e(absolute(path+"/" if path else ""))}</loc><lastmod>{C["updated"]}</lastmod>{image_xml}</url>\n'
OUTPUT['sitemap.xml']='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n'+''.join(sitemap_entry(path,photo) for path,title,photo in PAGES)+'</urlset>\n'
OUTPUT['robots.txt']=f'User-agent: *\nAllow: /\n\nSitemap: {absolute("sitemap.xml")}\n'
if INDEX:
    OUTPUT['robots.txt']+=f'\nUser-agent: Yandex\nAllow: /\nClean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term&yclid&gclid&gbraid&wbraid {urlparse(SITE).path or "/"}\n'
OUTPUT['assets/build-info.json']=json.dumps({'site_url':SITE,'indexable':INDEX,'updated':C['updated'],'pages':len(PAGES)},ensure_ascii=False,indent=2)+'\n'

parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
changed=[]
for name,contents in OUTPUT.items():
    dest=ROOT/name
    if args.check:
        if not dest.exists() or dest.read_text()!=contents:changed.append(name)
    else:
        dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(contents,encoding='utf-8')
if changed:raise SystemExit('Generated files differ; run python3 scripts/build.py: '+', '.join(changed))
print(f'{"Checked" if args.check else "Built"} {len(PAGES)} index candidates + privacy + 404; indexing={INDEX}; URL={SITE}')
